language: ruby
cache: bundler
rvm:
  - 2.5.6
before_install:
  - gem install bundler --version '~> 1.16'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URL="postgres://postgres@localhost/travis_ci_test"
